baseURL = 'https://mixie.ca/'
languageCode = 'en-us'
title = 'Mixie'

googleAnalytics = "G-C0TS5FNMW6"

[module]
[[module.imports]]
    path = 'github.com/adityatelange/hugo-PaperMod'

paginate = 5
enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
mainsections = [ "posts", "papermod" ]

[minify]
disableXML = true

[languages.en]
languageName = "English"
weight = 1

  [languages.en.taxonomies]
  tag = "tags"

  [[languages.en.menu.main]]
  name = "Domains"
  url = "domains"

  [[languages.en.menu.main]]
  name = "Agile Coaching"
  url = "agile-coaching"

  [[languages.en.menu.main]]
  name = "Accessibility"
  url = "accessibility"

  [[languages.en.menu.main]]
  name = "Development"
  url = "development"

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
env = "production"
description = "Mixie is a software development agency that builds custom software for businesses."
author = "Mixie"
social = true
defaultTheme = "light"
disableThemeToggle = true
ShowShareButtons = false
ShowReadingTime = false
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = false
ShowRssButtonInSectionTermList = true
ShowAllPagesInArchive = true
ShowPageNums = true
ShowToc = false
images = [ "images/papermod-cover.png" ]
hideMeta = true

  [params.assets]
  disableHLJS = true

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[services.instagram]
disableInlineCSS = true

[services.x]
disableInlineCSS = true
